### ISSUE TITLE
请教一下 API 的获取途径

### ISSUE THREAD

**Issue by cloudaemon** [mozillazg/python-shanbay#9]
您好，想问一下这个 API 的规范是怎么获取的呢？

我在网上只搜到 https://www.x0y1.com/developer/wiki/api/ 这个，其只有 token 的登录方式。

我通过浏览器的开发者工具看到扇贝网使用密码登录的方式是 `post` 一个 `account`+`password` 的方式，但是您的实现是使用 `put`，并且传了 `username`+`password`:

在这个函数里
https://github.com/mozillazg/python-shanbay/blob/d505ba614dc13a36afce46969d13fc64e10dde0d/shanbay/__init__.py#L68
写道：
```python
payload = {
            'username': self.username,
            'password': self.password,
        }
        headers = kwargs.setdefault('headers', {})
        headers.setdefault(
            'Referer',
            'https://www.shanbay.com/web/account/login'
        )
        url = 'https://www.shanbay.com/api/v1/account/login/web/'
        response = self.request(url, 'put', json=payload, **kwargs)
```
能告诉我这个方法是怎么来的吗？谢谢你了。

**Comment by mozillazg** [comment]
这个就是几年前他们页面上发送的请求（也是通过开发者工具看到的），如果现在不一样了可能是现在变了。

**Comment by cloudaemon** [comment]
原来如此，多谢。
